### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by NicoleZA** [EddyVerbruggen/nativescript-email#4]
I get the following error on my Samsung S5 android phone:

"All apps associated with this action have been disabled, blocked, or are not installed."

I am running android 6.0.1

**Comment by NicoleZA** [comment]
Ok. I think I have found the problem. It seems to work only if you have an attachment.
So, to fix the problem I moved      

```
  mail.setType("message/rfc822");
  mail.setAction(android.content.Intent.ACTION_SEND_MULTIPLE);
```

out of the _if (arg.attachments) {...._ section in email.android.js and it now works with or without attachments.

**Comment by EddyVerbruggen** [comment]
Hey @NicoleZA thanks for reporting this!

Since I don't have an Android 6 device... can you do me a favor and check if it would also work if you reverted your local changes and only commented out [this line](https://github.com/EddyVerbruggen/nativescript-email/blob/master/email.android.js#L57)? I don't think that should be there.

Thanks!
Eddy

**Comment by NicoleZA** [comment]
OK.  Sure. I have left the office, but will test it Monday and let you know

**Comment by EddyVerbruggen** [comment]
👍 Thanks in advance!

**Comment by NicoleZA** [comment]
I tried what you suggested, but it didn't work.
however
I did delete that line but also still moved this code above the _if (arg.attachments) {_ line
`
  mail.setType("message/rfc822");
  mail.setAction(android.content.Intent.ACTION_SEND_MULTIPLE);
`
and this works

**Comment by EddyVerbruggen** [comment]
Thanks Nicole, really appreciate you testing this. I'm releasing 1.3.1 with your suggested fix.
